### PR TITLE
allow user to pass in regex for resource lookup

### PR DESCRIPTION
**Pull request by clnperez**
dhcp networks are given a name at create-time by the dhcp service, so we won't know network name -OR- ID until after it's created. we'll have to settle for this, which will create a one-DHCP-nw-per-cloud-instance restriction until we can get a feature request accepted and implemented by powervs

Signed-off-by: Christy Norman <christy@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by Karthik-K-N** [comment]
If this has to be done then we may need to remove this check in mapio webhook https://github.com/openshift/machine-api-operator/pull/998/files#r831762016

**Review by mkumatag — CHANGES_REQUESTED** [review]
I avoid such logic into the controller code because there may be good chance in the future where they may change the naming pattern itself.

Instead I'm wondering if we can add one more field called `regex` [here](https://github.com/openshift/machine-api-provider-powervs/blob/89bb5bec120eb71f9404cc86795a802024fcb2e8/pkg/apis/powervsprovider/v1alpha1/powervsmachineproviderconfig_types.go#L69) so that the calling code can specify whatever regex they want.

wdys @Karthik-K-N @clnperez

**Comment by Karthik-K-N** [comment]
> I avoid such logic into the controller code because there may be good chance in the future where they may change the naming pattern itself.
> 
> Instead I'm wondering if we can add one more field called `regex` [here](https://github.com/openshift/machine-api-provider-powervs/blob/89bb5bec120eb71f9404cc86795a802024fcb2e8/pkg/apis/powervsprovider/v1alpha1/powervsmachineproviderconfig_types.go#L69) so that the calling code can specify whatever regex they want.
> 
> wdys @Karthik-K-N @clnperez

Yeah, I think this approach looks good to me, By this way we can add validation as well for Network.

**Comment by clnperez** [comment]
ah yah, that's a good idea to have the regex not be hardcoded in the controller itself. i can resubmit with that today

**Comment by clnperez** [comment]
No matter what I do for that import statement, these tests fail. I changed it to what the generate outputs but then it complains with the opposite reason.

**Review by mkumatag — CHANGES_REQUESTED** [review]
one minor comment, otherwise lgtm

**Comment by clnperez** [comment]
added that json line, rebased, and re-pushed 🤞🏻

**Comment by clnperez** [comment]
this is stuck. github is being odd lately
/retest

**Review by mkumatag — APPROVED** [review]
/lgtm
/approve

@Karthik-K-N lets submit any other changes required anywhere for the validate.

**Pull request merged**
