### PR TITLE
Update k8s to 1.25

### PR DESCRIPTION
**Pull request by Karthik-K-N**
Aligning with other mapi providers updating k8s to 1.25 and update openshift/api

### CODE REVIEW

**Comment by JoelSpeed** [comment]
We have no E2E here, has this new build been tested?

**Comment by Karthik-K-N** [comment]
> We have no E2E here, has this new build been tested?

I am currently testing locally against a cluster, Will update the results here once done
/hold

**Comment by Karthik-K-N** [comment]
Tested with a cluster and could see machine provision workflow working as expected
```
karthikkn@Karthiks-MacBook-Pro cmd % oc -n openshift-machine-api get machine
NAME                                     PHASE     TYPE   REGION   ZONE    AGE
powervs-actuator-testing-machine-cs4q4   Running   s922   sao      sao01   15m
rdr-kn85-j4k4f-master-0                  Running   s922   sao      sao01   14d
rdr-kn85-j4k4f-master-1                  Running   s922   sao      sao01   14d
rdr-kn85-j4k4f-master-2                  Running   s922   sao      sao01   14d
rdr-kn85-j4k4f-worker-4lzhg              Running   s922   sao      sao01   5d2h
rdr-kn85-j4k4f-worker-cddzh              Running   s922   sao      sao01   5d2h
rdr-kn85-j4k4f-worker-kmwxg              Running   s922   sao      sao01   5d2h
```

/hold cancel

**Pull request merged**
