### PR TITLE
MULTIARCH-4993: Add multiarch reviewers and approvers to OWNER file

### PR DESCRIPTION
**Pull request by Karthik-K-N**

### CODE REVIEW

**Comment by mkumatag** [comment]
/cc @jaypoulz 

ptal

**Comment by jaypoulz** [comment]
/lgtm
Thanks for doing this!

**Comment by jaypoulz** [comment]
TRT set the 'acknowledge-critical-fixes-only` for Shift week. This should proceed automatically once this is removed at the end of the week.

**Comment by Karthik-K-N** [comment]
@jaypoulz can this be merged now?

**Comment by mkumatag** [comment]
> @jaypoulz can this be merged now?

Its waiting on `Needs jira/valid-reference label.`

**Pull request merged**
