### PR TITLE
OCPBUGS-46471: Sets Authenticator.URL with IAM endpoint override if provided

### PR DESCRIPTION
**Pull request by miyamotoh**

### CODE REVIEW

**Comment by mkumatag** [comment]
@miyamotoh once you are ready with the PR, please ping - @Karthik-K-N

**Review by Karthik-K-N — COMMENTED** [review]
@kishen-v FYI

Changes LGTM, but for this to work we need to first fix the custom-controller error

**Comment by miyamotoh** [comment]
@Karthik-K-N which "custom-controller" error are you referring to? If it's the `machine-controller` error failing to update `platformStatus` with endpoint overrides, I found a way on the installer side. PTAL https://github.com/openshift/installer/pull/9317

**Comment by Karthik-K-N** [comment]
> @Karthik-K-N which "custom-controller" error are you referring to? If it's the `machine-controller` error failing to update `platformStatus` with endpoint overrides, I found a way on the installer side. PTAL [openshift/installer#9317](https://github.com/openshift/installer/pull/9317)

Got it your point, But I am not sure how good that practice is, But that's unrelated to this so
/lgtm

**Comment by miyamotoh** [comment]
We have good disconnected IPI runs with this change, though with other changes as well. Let's chip away forward.

**Comment by mjturek** [comment]
/retitle OCPBUGS-46471: Sets Authenticator.URL with IAM endpoint override if provided

**Pull request merged**
